---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent

ignore: |
  node_modules/
  .git/
  */node_modules/
  01-introduction-horizontal-scalability/ecsdemo-*/
  08-cloud-networking-vpc/cloudformation/
